language: python

python:
  - 3.4

matrix:
  fast_finish: true
  allow_failures:
    - python: 3.3
    - python: nightly

install:
  - pip install -r requirements.txt

script:
  - python manage.py test -v 2
